CREATE DATABASE DUAN1_TEAM6;
GO

USE DUAN1_TEAM6;
GO

CREATE TABLE SANPHAM (
    ID VARCHAR(20) PRIMARY KEY,
    TenSanPham NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE MAUSAC (
    ID VARCHAR(20) PRIMARY KEY,
    TenMau NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
GO

CREATE TABLE SIZE (
    ID VARCHAR(20) PRIMARY KEY,
    Ten NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
GO

CREATE TABLE CHATLIEU (
    ID VARCHAR(20) PRIMARY KEY,
    Ten NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
GO

CREATE TABLE THUONGHIEU (
    ID VARCHAR(20) PRIMARY KEY,
    Ten NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
GO

CREATE TABLE SANPHAMCHITIET (
    ID VARCHAR(20) PRIMARY KEY,
    ID_SanPham VARCHAR(20),
    ID_MauSac VARCHAR(20),
    ID_Size VARCHAR(20),
    ID_ChatLieu VARCHAR(20),
    ID_ThuongHieu VARCHAR(20),
    GiaBan DECIMAL(20,0) NOT NULL,
    SoLuongTon INT NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_SanPham FOREIGN KEY (ID_SanPham) REFERENCES SANPHAM(ID),
    CONSTRAINT FK_MauSac FOREIGN KEY (ID_MauSac) REFERENCES MAUSAC(ID),
    CONSTRAINT FK_Size FOREIGN KEY (ID_Size) REFERENCES SIZE(ID),
    CONSTRAINT FK_ChatLieu FOREIGN KEY (ID_ChatLieu) REFERENCES CHATLIEU(ID),
    CONSTRAINT FK_ThuongHieu FOREIGN KEY (ID_ThuongHieu) REFERENCES THUONGHIEU(ID)
);
GO

CREATE TABLE NHANVIEN (
    ID VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    NamSinh INT NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    ChucVu BIT NOT NULL,
    MatKhau VARCHAR(50) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE KHACHHANG (
    ID VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(15) NOT NULL,
    Email VARCHAR(30) NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE VOUCHER (
    ID VARCHAR(20) PRIMARY KEY,
    TenVoucher NVARCHAR(50) NOT NULL,
    SoLuong INT NOT NULL,
    LoaiVoucher NVARCHAR(50) NOT NULL,
    MucGiamGia DECIMAL(20,3) NOT NULL,
    NgayBatDau DATETIME NOT NULL,
    NgayKetThuc DATETIME NOT NULL,
    MoTa NVARCHAR(255),
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE HOADON (
    ID VARCHAR(20) PRIMARY KEY,
    ID_NhanVien VARCHAR(20),
    ID_KhachHang VARCHAR(20),
    ID_Voucher VARCHAR(20),
    HinhThucThanhToan NVARCHAR(50),
    TongTien DECIMAL(20,0) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_NhanVien FOREIGN KEY (ID_NhanVien) REFERENCES NHANVIEN(ID),
    CONSTRAINT FK_KhachHang FOREIGN KEY (ID_KhachHang) REFERENCES KHACHHANG(ID),
    CONSTRAINT FK_Voucher FOREIGN KEY (ID_Voucher) REFERENCES VOUCHER(ID)
);
GO

CREATE TABLE HOADONCHITIET (
    ID VARCHAR(20) PRIMARY KEY,
    ID_HoaDon VARCHAR(20),
    ID_SanPhamChiTiet VARCHAR(20),
    SoLuong INT NOT NULL,
    ThanhTien DECIMAL(20,0) NOT NULL,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgaySua DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TrangThai NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_HoaDon FOREIGN KEY (ID_HoaDon) REFERENCES HOADON(ID),
    CONSTRAINT FK_SanPhamChiTiet FOREIGN KEY (ID_SanPhamChiTiet) REFERENCES SANPHAMCHITIET(ID)
);
GO
